[robot]
hardware = "R1_LITE"

[basic]
control_frequency = 30.0
step_mode = "sync"
action_steps = 32

[model]
ckpt_dir = "/data/trt_ckpts/"
use_trt = true
processor = "cuda" # Optional: 'cuda' for TensorRT, 'default' for Pytorch 

[instruction]
use_vlm = true
bbox_as_instruction = false
image_condition_lang_prefix = true
pp_lower_half = false
image_as_condition = true
